### ISSUE TITLE
Does this client support transactions?

### ISSUE THREAD

**Issue by mikehearn** [tikv/client-java#102]
I rummaged through the code and it looks like there is some support for KV transactions in this client, but I couldn't find any examples of how to actually do that. As transactions are a key feature of TiKV that was a surprise. Also the website says this client shouldn't be used, but there doesn't seem to be any plan or roadmap to bring it to maturity/release? Is the "do not use" warning still in effect and if so, why does this client exist?

**Comment by birdstorm** [comment]
Hi, @mikechengwei 

TiKV client provides basic APIs for transactions, but the current APIs are low-level and designed in `kv` format rather than `row` format. Some users have already asked about this question and we are planning to update these APIs to be used more easily. I will write a document about it later.
