### ISSUE TITLE
Range query using TiKV database

### ISSUE THREAD

**Issue by cyberquarks** [tikv/client-java#105]
How do you do range query with TiKV and java-client?

Suppose I have this model:

```java
public class Hub implements Serializable {
    private String name;
    private List<Schedule> schedules;
}
```

and 

```java
import java.time.LocalTime;

public class Schedule implements Serializable {
    private String day;
    private LocalTime opens; 
    private LocalTime closes;
}
``` 

How can I do a query that will satisfy this:

```java
new Schedule().builder()
    .day("Monday")
    .opens(LocalTime.parse("09:00")
    .close(LocalTime.parse("17:00").build();
```

 1. How do you store the `Hub` model into TiKV 
 2. And, how can you do a range query to the `schedules` in this example?

**Comment by marsishandsome** [comment]
1. How do you store the Hub model into TiKV
if you want to use TiKV directly without TiDB, you can encode Hub into a ByteString and store the ByteString into TiKV.

https://github.com/tikv/client-java/blob/v3.0.0/src/main/java/org/tikv/raw/RawKVClient.java#L82

1. And, how can you do a range query to the schedules in this example?

you can use scan API to do a range query

https://github.com/tikv/client-java/blob/v3.0.0/src/main/java/org/tikv/raw/RawKVClient.java#L152

**Comment by cyberquarks** [comment]
First question: how about when `Schedule` is actually embedded into `Hub` as a `List `as shown here:
```java
public class Hub implements Serializable {
    private String name;
    private List<Schedule> schedules;
}
```

Second question is a bit more complicated, the way `LocalTime` works in Java is that is is compared using the `compareTo` override meaning it compares whether a specific local time (not date) is greater than, equal or less than:

```java
@Override
    public int compareTo(LocalTime other) {
        int cmp = Integer.compare(hour, other.hour);
        if (cmp == 0) {
            cmp = Integer.compare(minute, other.minute);
            if (cmp == 0) {
                cmp = Integer.compare(second, other.second);
                if (cmp == 0) {
                    cmp = Integer.compare(nano, other.nano);
                }
            }
        }
        return cmp;
    }
 ```
 This one is the core Java implementation, but in case of `Schedule` which is a actually a range of LocalTime it is compared like this:
 
 ```java
   @Override
  public int compareTo(@NotNull Schedule range) {
    if((day.value) == range.getDay().value) {
      if ((range.lower.isBefore(lower) && range.upper.isBefore(lower)) && (range.lower.isBefore(upper)
              && range.upper.isBefore(upper))) {
        return -1;
      } else if ((range.lower.isAfter(lower) && range.upper.isAfter(lower)) && (range.lower.isAfter(
              upper)
              && range.upper.isAfter(upper))) {
        return 1;
      }
    } else if(day.value > range.getDay().value) {
      return 1;
    } else if(day.value < range.getDay().value) {
      return -1;
    }
    return 0;
  }
  ```
[  Here's the complete code for the Schedule class.](https://gist.github.com/cyberquarks/b66d6ca1c4fa335ef93c23a4a89961f0)
  
Anyway, what this codes does is to check for day, whether the days is even before, now or after. Then, if the day matches then that's the time it will check for the range if that matches the object two ranges. Simply put, it checks if the `Schedule range` in query is within the bounds of the `lower` and `upper` `LocalTime`s 

So for example I have a stored Hub with List of Schedules, say:

```java
Hub hubOne = new Hub();
List<Schedule> schedules = new ArrayList();

Schedule monday = new Schedule("Monday", "07:00", "17:00"); // so it's open on Mondays 7am to 5pm,
Schedule tuesday = new Schedule("Tuesday", "07:00", "23:59"); // so it's open on Tuesdays 7am to 11:59pm

schedules.add(monday);
schedules.add(tuesday);
hubOne.setSchedule(schedules);

Hub hubTwo = new Hub();
hubTwo.setSchedule(Arrays.asList(new Schedule("Monday", "06:00", "08:00"))); // Just open for 6am to 8am on Mondays
```

And then I want to look for `Hub`s that are open on Monday 9am to 5pm, so from the example above, `hubTwo` does not match and it should return `hubOne` because it is the one that have the schedule that is open 8am to 5pm, so it matches the query (in plain Java form), hence _in range_: 

```java
new Schedule().builder()
    .day("Monday")
    .opens(LocalTime.parse("09:00")
    .close(LocalTime.parse("17:00").build();
```
  
 And I'm not so sure how to apply this range scan `RawKVClient.scan("myencode_Monday_09:00", "myencode_Monday_17:00")` that will satisfy the same compare logic.

**Comment by birdstorm** [comment]
@cyberquarks Hi, I think you should use 2 columns of time to indicate a hub:

for example, 

`hubOne`: `myencode_Monday_17:00_07:00`
`hubTwo`: `myencode_Monday_08:00_06:00`

So when you try to find a range `09:00~17:00`, the range you are looking for is equivalent to:

range: `myencode_Monday_17:00 ~ myencode_Monday_24:00` where the start time is less than `09:00`

P.S. Not including cases when the hub is open for more than one day, or querying a range that crosses 24:00 midnight.
If something like that happens, try to use timestamp instead of `Monday`

**Comment by questionaut** [comment]
Hi @birdstorm I'm also interested to learn about TiKV, how do you actually save a POJO? Following through this thread, it mentions that it saves by serializing into ByteString. 

However, the given example above by the author:

```java
public class Hub implements Serializable {
    private String name;
    private List<Schedule> schedules;
}
```
Can you really just encode it and put it into TiKV and be able to query for its fields, e.g. _name_ and _schedules_? 
I mean like:

`RawKVClient.put(whateverKey, encodeToByteString(hub));` ?

If not, what the proper way to encode it as such the fields  _name_ and _schedules_ (and other fields if any) can be queried? 

I'm also curious to know the details from your answer above, does 'LocalTime' translate to a key or keys that can be queried? Moreso query in terms of comparing if a query range falls within any stored ranges of `LocalTime` in the given example? In my experience with Key-value stores, you can't query fields inside it, you can just query the keys that the whole object was saved with? 

Can you explain further?

**Comment by birdstorm** [comment]
> Hi @birdstorm I'm also interested to learn about TiKV, how do you actually save a POJO? Following through this thread, it mentions that it saves by serializing into ByteString.
> 
> However, the given example above by the author:
> 
> ```java
> public class Hub implements Serializable {
>     private String name;
>     private List<Schedule> schedules;
> }
> ```
> 
> Can you really just encode it and put it into TiKV and be able to query for its fields, e.g. _name_ and _schedules_?
> I mean like:
> 
> `RawKVClient.put(uuid(), encodeToByteString(hub));` ?
> 
> If not, what's the proper way to encode it as such the fields _name_ and _schedules_ (and other fields if any) can be queried?
> 
> I'm also curious to know the details from your answer above, does 'LocalTime' translate to a key or keys that can be queried? Moreso query in terms of comparing if a query range falls within any stored ranges of `LocalTime` in the given example? In my experience with Key-value stores, you can't query fields inside it, you can just query the keys that the whole object was saved with?
> 
> Can you explain further?


Hi, @cyberquarks 

I think there are several questions to be answered, so I will explain them one by one.

LocalTime can be translated to a key by interpreting it into string `09:00` or into timestamp `32400(9*60*60)`, it depends on your means of usage as long as the encoded key is ordered.

As you have mentioned, key-value stores cannot query fields inside them, so you have to specify a range to query, and decode the fields to filter out your result(in your client).

To my understanding, you wish to push down some computation operations to TiKV, and use APIs to query something like `range(field1, a, b) AND range(field2, a, b)`, i.e., queries like SQL. In short, that is not possible if TiKV doesn't know your schema. 

But there are workarounds. If the query itself is not complicated, it can be done by carefully designing the encoded key-value format, so that the pairs remain ordered and can be queried by range scans + filters.

When the query is complicated, you have to provide schema, for example, by using TiDB's schema. So in that case I would suggest you use TiDB instead.

If you feel ok not to push down the computation, you can just design your own schema, and store it somewhere in TiKV, and read it when the `kv` is read from storage. e.g., in the `hubOne` case, store your schema as `schema_prefix_hubName_schedules`, and when a query comes with range `[start, end)`, decode the schedules and filter out those that match your query.

Hope it helps:)
