### ISSUE TITLE
need optimize of RawKVClient constructor?

### ISSUE THREAD

**Issue by honeychen502** [tikv/client-java#20]
current now, constructor is code like this:
private RawKVClient(String addresses)

similary, constructor of TxtKVClient maybe like this:
private TxtKVClient(String addresses)

So, TiSession.create will be called twice or more times, and create multiple TiSession instance,.

Optimize propose：
should we constraints the constructor of both RawKVClient and TxtKVClient replace by passing TiSession instance directly, instance of addresses string?

Thus, code is:
private RawKVClient(TiSession sessionj)
private TxtKVClient(TiSession sessionj)

**Comment by birdstorm** [comment]
Nice catch. Unfortunately, Raw and Txn client cannot be used at the same time. Mixing RAW/TXN mode will cause possible incorrect data problems because they might share the same key pattern, btw TXN can only decode the encoded key and values. If the client decodes a raw kv-pair when using TXN mode, it will reveal unexpected result.

**Comment by birdstorm** [comment]
I will make the constructor support using TiSession along with String.

**Comment by birdstorm** [comment]
Done by #18
